{{- if .Values.enabled }}
{{- range .Values.config.cluster_secret_stores }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
spec:
{{ toYaml .spec | indent 2 }}
{{- end }}
{{- end }}
