---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "{{ .Values.provider.gcpsm.projectID | lower }}"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "5"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "5"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.provider.gcpsm.projectID }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: "{{ .Values.clusterName }}-day2-gitops"
            namespace: "{{ .Values.tf_resources_namespace }}"
            key: credentials.json
  ## Provider configs for Workload Identity Federation (WIF) - Currently not supported by ESO.
  # provider:
  #   gcpsm:
  #     projectID: {{ .Values.provider.gcpsm.projectID }} # Override per ExternalSecret
  #     auth:
  #       workloadIdentity:
  #         clusterLocation: {{ .Values.clusterLocation }}
  #         clusterName: {{ .Values.clusterName }}
  #         clusterProjectID: {{ .Values.provider.gcpsm.projectID }}
  #         serviceAccountRef:
  #           name: "{{ .Values.clusterName }}-day2-gitops"
  #           namespace: {{ .Values.tf_resources_namespace }}