---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "{{ .Values.provider.gcpsm.projectID | lower }}"
  annotations:
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "5"
    # "helm.sh/hook": ""
    "helm.sh/hook-weight": "5"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.provider.gcpsm.projectID }}
      auth:
        workloadIdentity:
          clusterName: {{ .Values.clusterName }}
          serviceAccountRef:
            name: "{{ .Values.clusterName }}-day2-gitops"
            namespace: "{{ .Values.tf_resources_namespace }}"