enabled: false
secretStoreName: platform-secrets
idp:
  openid:
    enable: false
    oauthCertsConfigMapName: oauth-config-certs
    providers:
      - name: example-oidc
        enabled: true
        clientID: changeme
        clientSecretSecretName: example-oidc-client-secret
        remoteSecretKey: example-oidc-client-secret
        issuerURL: https://issuer.example.com/realms/platform
        extraScopes:
          - profile
          - openid
        extraAuthorizeParameters:
          include_granted_scopes: "true"
        claims:
          preferredUsername:
            - preferred_username
            - email
          name:
            - name
            - given_name
          email:
            - email
          groups:
            - groups
