enabled: true
config:
  name: cluster
  external_secrets_namespace: external-secrets-operator
  refresh_interval: 1h
  cluster_secret_stores:
    - name: platform-secrets
      namespace: ""
      spec:
        provider:
          gcpsm:
            projectID: changeme-project
            auth:
              workloadIdentityFederation:
                audience: "//iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/gcp-classic-day2-gitops/providers/gcp-classic-day2-gitops"
                serviceAccountRef:
                  name: external-secrets-operator
                  namespace: external-secrets-operator
