{{- if and .Values.enabled .Values.provider.credentials.data }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.provider.credentials.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStoreName }}
  data:
{{- range .Values.provider.credentials.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey | quote }}
{{- end }}
  target:
    name: {{ .Values.provider.credentials.secretName }}
    creationPolicy: Owner
{{- end }}
