namespace: external-secrets-operator
clusterName: "changeme"
clusterLocation: "global"
tf_resources_namespace: "ocp-tf-resources"
clusterSecretStoreName: example-gcp-project
provider: # Using Workload Identity (WIF)
  gcpsm:
    projectID: example-gcp-project
    