clusterName: "osd-lbarry-101"

clusterSecretStoreName: example-gcp-project
patchSchedule: "*/5 * * * *"

registriesTrustedCerts: # Provide list of registry and key vault secret name
  - registryHost: hostname.example.com
    caKeyVaultSecretName: hostname-example-com-registry-certificates