{{- range .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
{{ toYaml .annotations | indent 4 }}
{{- end }}
