namespace: openshift-compliance
clusterName: "changeme"
resourceCommonName: "pci-dss-compliance"

scanProfiles:
  - ocp4-pci-dss
autoApplyRemediations: false
enableDebug: false
scanSchedule: 0 5 * * * # https://crontab.guru/
