clusterName: "osd-lbarry-101"
clusterSecretStoreName: example-gcp-project
hecSecretName: splunk-logging-hec-token
splunk:
  endpoint: http://your.splunk.hec.url:8088/services/collector
  indexName: openshift
